magentix_sylius_pickup_checkout_pickup_list:
    path: /pickup-list/{method}
    defaults:
        _controller: magentix.sylius_pickup.controller:list

magentix_sylius_pickup_ajax_pickup_list:
    path: /pickup-list
    methods: [GET]
    defaults:
        _controller: magentix.sylius_pickup.controller:list
